### ISSUE TITLE
Borders

### ISSUE THREAD

**Issue by mgwio** [traxium/tabtree#106]
Hi,

Is there something that is continuously overwriting border settings somewhere? DOM inspector shows that the borders on the sidebar are set to `1px none rgb(128,128,128)`, but none of the CSS sources tell the origin, and they're impossible to change using Stylish or directly editing from the DOM inspector.

Edit: Unrelated, but have you given your implementation of favicons a selector? Trying to hide them is also an exercise in futility. It looks like they're constantly being reloaded?

**Comment by traxium** [comment]
Although `#tt-sidebar` has 0px borders on my system (both Default and Developer Edition themes) I'd recommend you to use:

``` CSS
#tt-sidebar {
  -moz-appearance: none;
}
```

`-moz-appearance: none;` also useful for any element if it doesn't accept your CSS.

**Comment by traxium** [comment]
> Edit: Unrelated, but have you given your implementation of favicons a selector? Trying to hide them is also an exercise in futility. It looks like they're constantly being reloaded?

If you are talking about `<tree>` favicons they are set by JavaScript here https://github.com/traxium/tabtree/blob/v1.4.5/bootstrap.js#L1914. If that function returns `""` then `::moz-tree-image` is used, e.g.:

``` CSS
.tt-treechildren::-moz-tree-image {
    list-style-image: url(chrome://mozapps/skin/places/defaultFavicon.png);
    padding-right: 2px;
    margin: 0 2px;
    width: 16px;
    height: 16px;
}
```

If you are talking about pinned tab favicons they are essentially `<toolbarbutton class="tt-tab-button">` wrapped in <ttpinnedtab>. See https://github.com/traxium/tabtree/blob/v1.4.5/bindings.xml for more details.

**Comment by mgwio** [comment]
Great. When I was experimenting I found the borders are part of the tree and not the sidebar, and 

``` css
.tt-tree {
  -moz-appearance: none!important;
}
```

worked perfectly. I'll mess around with the favicons. Would you be interested in a pull request to make them toggleable?
