### ISSUE TITLE
Sound icon also shortening other tabs’ title

### ISSUE THREAD

**Issue by ariasuni** [traxium/tabtree#107]
When playing a video/sound on Firefox, a sound icon appear in the tab after the title, but it also shorten the other tabs’ title like there was also a sound icon in all tabs.

Not critical but annoying.

**Comment by mgwio** [comment]
+1
I've just hidden it with

``` css
#tt #tt-overlay {
    display: none!important;
}
```

in Stylish as a band-aid fix.
