### ISSUE TITLE
Firefox 49 crashes when unhiding Tab Tree in certain conditions

### ISSUE THREAD

**Issue by dkasak** [traxium/tabtree#173]
Firefox 49 crashes for me with the latest Tab Tree in AMO if:
1. Tab Tree's position setting is set to `Left`.
2. There are more tabs than can be displayed on the screen at once so Tab Tree's scrollbar appears.
3. Tab Tree is hidden (by pressing `F8`, by default) and then unhidden (by pressing `F8` again).

Tab Tree then freezes very shortly (for about a second) and then the browser crashes.

I've tried stepping the addon in Firefox's JS debugger and it appears to crash after stepping into [this line](https://github.com/traxium/tabtree/blob/master/bootstrap.js#L3101).

I've managed to reproduce this on a clean profile with only Tab Tree installed and I'm on Arch Linux.

**Comment by dgaletic** [comment]
I have the same bug with Firefox 49 on Linux Mint 17.3.
It doesn't seem to depend on the number of tabs that were open _prior_ to hiding Tab Tree, as it:
a) didn't crash if I closed excessive tabs while Tab Tree was hidden, and 
b) crashed if I opened additional tabs while it was hidden (enough to invoke the scroll bar).

**Comment by Fabiensk** [comment]
Concerning the bug #176 : my video card is  an AMD A8-7600 processor with an integrated Radeon R7.

**Comment by traxium** [comment]
Couldn't confirm on FF 49.0.2 Mint 18 VMware. What's your video card manufacturer, Intel?
Line `aDOMWindow.document.documentElement.removeAttribute("tt-auto-hide-when-maximized");` triggers these CSS rules from tt-auto-hide.css:

``` CSS
#main-window[sizemode="maximized"][tt-auto-hide-when-maximized] #tt-toggler {
    visibility: visible;
}

#main-window[sizemode="maximized"][tt-auto-hide-when-maximized] #tt-sidebar,
#main-window[sizemode="maximized"][tt-auto-hide-when-maximized] #tt-splitter {
    visibility: collapse;
}
```

Most likely Firefox crashes when #tt-sidebar becomes visible. Try adding and unchecking `visibility: collapse` to #tt-sidebar. If Firefox crashes try `display: none` instead:

![mint 18 cinnamon 64-bit-2016-11-13-19-26-24](https://cloud.githubusercontent.com/assets/13660441/20247229/f6407378-a9d7-11e6-9410-e38cf32ef820.png)
