### ISSUE TITLE
Remove pinned tabs toolbar at the top?

### ISSUE THREAD

**Issue by kefkf** [traxium/tabtree#22]
Is there an option to remove or hide the space for the pinned tabs at the top of the tabs toolbar?

**Comment by traxium** [comment]
Fast way using Stylish or userChrome.css:

``` css
@namespace url(http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul);

#tt-toolbox {
  visibility: collapse;
}
```

This issue will be fixed when I improve pinned tabs in order to resolve issues #8, #9, #10 and all other issues related to pinned tabs (it's going to be automatically collapsed or something like that when there are no pinned tabs).
