### ISSUE TITLE
[OSX] The back button is broken when the Nav Bar Height is below 32px

### ISSUE THREAD

**Issue by bpierre** [traxium/tabtree#66]
Tested on `Nightly 46.0a1 (2016-01-04)` only, it may be something new in the Firefox UI styles.

<img width="436" alt="screen shot 2016-01-04 at 15 36 53" src="https://cloud.githubusercontent.com/assets/36158/12093150/1b9456e8-b2f9-11e5-8277-d5f8bdf690cf.png">

**Comment by traxium** [comment]
I don't have this bag on 46.0a2 (2016-02-02):

![os x mountain lion-2016-02-02-16-23-57](https://cloud.githubusercontent.com/assets/13660441/12750647/7bfc350a-c9c9-11e5-8ac5-aa26196825bd.png)

The back button image may be missing because I didn't care about `@media (min-resolution: 1.1dppx)` and `@media (min-resolution: 2dppx)`. You can check this with this css (adding `!important` if necessary):

``` CSS
  #back-button {
    -moz-image-region: rect(0, 72px, 36px, 36px);
  }

  #forward-button {
    -moz-image-region: rect(0, 144px, 36px, 108px);
  }
```

And I also don't see proper borders and the back button background-color on your screenshot. You can try to restore the back button borders with (adding `!important` if necessary):

``` CSS
    #back-button:not(:-moz-lwtheme),
    #forward-button:not(:-moz-lwtheme) {
        border-color: hsla(0,0%,0%,.35) hsla(0,0%,0%,.25) hsla(0,0%,0%,.2);
        box-shadow: inset 0 1px 0 hsla(0,0%,100%,.2),
        inset 0 0 1px hsla(0,0%,100%,.1),
        0 1px 0 hsla(0,0%,100%,.2);
    }

    #back-button:hover:active:not(:-moz-lwtheme),
    #forward-button:hover:active:not(:-moz-lwtheme) {
        border-color: hsla(0,0%,0%,.43) hsla(0,0%,0%,.25) hsla(0,0%,0%,.37);
        box-shadow: inset 0 1px 0 hsla(0,0%,0%,.02),
        inset 0 1px 2px hsla(0,0%,0%,.2),
        0 1px 0 hsla(0,0%,100%,.2);
    }

    #back-button:-moz-window-inactive:not(:-moz-lwtheme),
    #forward-button:-moz-window-inactive:not(:-moz-lwtheme) {
        border-color: hsla(0,0%,0%,.2);
    }
```

There are also missing borders on #urlbar on your screenshot. But I didn't touch them in my styles. Conclusion: this bugs won't be fixed soon because I can't reproduce them now. If something mentioned above helps then I'll add it in the next release.

**Comment by bpierre** [comment]
It looks like you have the Dev Edition theme? You can see the default Firefox theme (even on Firefox Dev Edition) by following these instructions: https://developer.mozilla.org/en-US/Firefox/Developer_Edition/Reverting

**Comment by traxium** [comment]
I tried both:
![os x mountain lion-2016-02-02-17-09-38](https://cloud.githubusercontent.com/assets/13660441/12751760/0750d0a6-c9d0-11e5-9bb6-233aebb74488.png)
![os x mountain lion-2016-02-02-17-10-46](https://cloud.githubusercontent.com/assets/13660441/12751769/13d9dcf0-c9d0-11e5-8c4a-ba8c79d0af58.png)
And I just looked closer at your screenshot. And it's bigger (has more `dppx`) then mine. So I really should pay more attention to this `@media (min-resolution: 1.1dppx)` stuff. The comparison in natural sizes:
![dppx](https://cloud.githubusercontent.com/assets/13660441/12752026/7d6578ae-c9d1-11e5-9b6f-aa2e0eff1b7c.png)

**Comment by traxium** [comment]
By the way. I use VMware Workstation with OS X Mountain Lion 10.8.3 installed on it.

**Comment by traxium** [comment]
The back button should be fixed. But I didn't test it.

I added:

``` CSS
@media (min-resolution: 2dppx) {
    #back-button {
        -moz-image-region: rect(0, 108px, 36px, 72px);
    }

    #back-button:hover:active:not([disabled="true"]) {
        -moz-image-region: rect(36px, 108px, 72px, 72px);
    }
}
```

There was just:

``` CSS
#back-button {
    -moz-image-region: rect(0, 54px, 18px, 36px);
}

#back-button:hover:active:not([disabled="true"]) {
    -moz-image-region: rect(18px, 54px, 36px, 36px);
}
```
