### ISSUE TITLE
[Feature] Provide a way to change the items height

### ISSUE THREAD

**Issue by bpierre** [traxium/tabtree#67]

**Comment by raphaelbastide** [comment]
I agree, I would love to increase items’ height to make it more accessible.

**Comment by mtpc** [comment]
:+1:

**Comment by traxium** [comment]
As for now you can use Stylish or userChrome.css

``` CSS
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");

#tt-treechildren::-moz-tree-row,
#tt-treechildren-feedback::-moz-tree-row {
    min-height: 18px;
    height: 6em;
}
```

![tabtree 67](https://cloud.githubusercontent.com/assets/13660441/12228169/a25d63c8-b848-11e5-837e-601d3c994a35.PNG)
